### ISSUE TITLE
tally is only available in Ruby 2.7 and above 

### ISSUE THREAD

**Issue by UziaKAmobee** [ruby/rexml#203]
throw exception:
CHECK TOKEN EXCEPTION!!!! undefined method `tally' for ["quot", "quot"]:Array

https://github.com/ruby/rexml/pull/194/files

**Comment by olleolleolle** [comment]
Thanks for your report, but the linked PR implements a Refinement for any Ruby where `#tally` is not implemented.

Please reopen with a minimal reproduce script in the context of this repository's code to show in practice what fails.

Hope this helps!

**Comment by UziaKAmobee** [comment]
undefined method `tally' for ["quot", "quot"]:Array
/app/vendor/bundle/ruby/2.6.0/gems/rexml-3.3.8/lib/rexml/parsers/baseparser.rb:582:in `unnormalize'
/app/vendor/bundle/ruby/2.6.0/gems/rexml-3.3.8/lib/rexml/parsers/streamparser.rb:44:in `parse'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/xml/parser/engines/rexml.rb:19:in `parse'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/xml/parser.rb:44:in `parse'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/body.rb:37:in `parse'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/body.rb:23:in `apply'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/parser.rb:32:in `extract_body'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/parser.rb:13:in `apply'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/handler.rb:8:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/response.rb:45:in `block in on'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:139:in `block in on_success'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:166:in `block in listener'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:130:in `on_done'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:137:in `on_success'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/response.rb:44:in `on'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/handler.rb:8:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/endpoint_pattern.rb:27:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/endpoint_discovery.rb:67:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_url_encoded_keys.rb:40:in `manage_keys'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_url_encoded_keys.rb:32:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/request.rb:70:in `send_request'
/app/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'

**Comment by abdelbk** [comment]
Hi @olleolleolle. I believe there is indeed a bug with ruby versions prior to 2.7

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  ruby "2.5.9"

  gem "rexml", "3.4.0"
end

REXML::Parsers::BaseParser.class_eval do
  def unnormalize(string, entities=nil, filter=nil)
    [].tally
  end
end

parser = REXML::Parsers::BaseParser.new("")
parser.unnormalize("")
```

**Comment by kou** [comment]
Refinements works only in the same file. So the Ruby script you shared didn't work. (But `Enumerable#tally` works in `lib/rexml/parsers/baseparser.rb`.)
