### ISSUE TITLE
SystemStackError

### ISSUE THREAD

**Issue by pdobb** [ruby/rexml#26]
I'm not sure why this would be new to me... but I'm getting a `stack level too deep (SystemStackError)` from REXML when running [pronto-rubocop](https://github.com/prontolabs/pronto-rubocop), caused by line 79 here: https://github.com/ruby/rexml/blob/master/lib/rexml/xmldecl.rb#L74-L85

I tried adding a breakpoint to be sure and I can see it looping on the `self.old_enc = enc` line, over and over (since `old_enc=` is aliased to `encoding=`). Here's my stacktrace:
```
	11909: from /Users/pauld/.gem/ruby/2.5.3/bin/pronto:23:in `<main>'
	11908: from /Users/pauld/.gem/ruby/2.5.3/bin/pronto:23:in `load'
	11907: from /Users/pauld/.gem/ruby/2.5.3/gems/pronto-0.10.0/bin/pronto:6:in `<top (required)>'
	11906: from /Users/pauld/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11905: from /Users/pauld/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	11904: from /Users/pauld/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11903: from /Users/pauld/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11902: from /Users/pauld/.gem/ruby/2.5.3/gems/pronto-0.10.0/lib/pronto/cli.rb:52:in `run'
	 ... 11897 levels...
	    4: from /Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/xmldecl.rb:79:in `encoding='
	    3: from /Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/xmldecl.rb:79:in `encoding='
	    2: from /Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/xmldecl.rb:79:in `encoding='
	    1: from /Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/xmldecl.rb:79:in `encoding='
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/xmldecl.rb:75:in `encoding=': stack level too deep (SystemStackError)
```

For what it's worth, I'm also seeing tons of warnings:

```
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:99: warning: already initialized constant REXML::Parsers::BaseParser::ENTITYVALUE
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:94: warning: previous definition of ENTITYVALUE was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:100: warning: already initialized constant REXML::Parsers::BaseParser::PEDEF
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:95: warning: previous definition of PEDEF was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:101: warning: already initialized constant REXML::Parsers::BaseParser::ENTITYDEF
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:96: warning: previous definition of ENTITYDEF was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:102: warning: already initialized constant REXML::Parsers::BaseParser::PEDECL
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:97: warning: previous definition of PEDECL was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:103: warning: already initialized constant REXML::Parsers::BaseParser::GEDECL
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:98: warning: previous definition of GEDECL was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:104: warning: already initialized constant REXML::Parsers::BaseParser::ENTITYDECL
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:99: warning: previous definition of ENTITYDECL was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:106: warning: already initialized constant REXML::Parsers::BaseParser::EREFERENCE
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:101: warning: previous definition of EREFERENCE was here
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:108: warning: already initialized constant REXML::Parsers::BaseParser::DEFAULT_ENTITIES
/Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/parsers/baseparser.rb:103: warning: previous definition of DEFAULT_ENTITIES was here
```

And on and on for about 276 lines/warnings before the SystemStackError occurs.

**Comment by kou** [comment]
It seems that you mix system REXML and gem version REXML:

System REXML:

```text
	    1: from /Users/pauld/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml/xmldecl.rb:79:in `encoding='
```

Gem version REXML:

```text
/Users/pauld/.gem/ruby/2.5.3/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:108: warning: already initialized constant REXML::Parsers::BaseParser::DEFAULT_ENTITIES
```

**Comment by pdobb** [comment]
Thank you, @kou! 

I apparently have a lack of knowledge/understanding about this "system gems" thing. I renamed `~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rexml` to `rexml.old` and that fixed my issue. Closing this ticket since it was my fault. Still don't get how that method I linked to isn't always just an infinite loop, though.
