### ISSUE TITLE
Xpath with leading predicate gives error

### ISSUE THREAD

**Issue by shorowit** [ruby/rexml#27]
I'm updating from ruby 2.2 and REXML is now giving an error whenever an XPath expression starts with a predicate.

Example
```
xml_string = <<EOF
<A>
  <B/>
</A>
EOF

xml_doc = REXML::Document.new(xml_string)

puts REXML::XPath.first(xml_doc.elements['A'], '[B]')
```

Ruby 2.2:
```
<A>
  <B/>
</A>
```

Ruby 2.7:
```
Traceback (most recent call last):
        4: from C:/Users/shorowit/Desktop/test.rb:13:in `<main>'
        3: from C:/Ruby27-x64/lib/ruby/2.7.0/rexml/xpath.rb:39:in `first'
        2: from C:/Ruby27-x64/lib/ruby/2.7.0/rexml/xpath_parser.rb:75:in `parse'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rexml/xpath_parser.rb:138:in `match'
C:/Ruby27-x64/lib/ruby/2.7.0/rexml/xpath_parser.rb:427:in `expr': [BUG] Unexpected path: <:predicate>: <[[:child, :qname, "", "B"]]> (RuntimeError)
```

**Comment by shorowit** [comment]
Is there a workaround to perform this operation in ruby 2.7?

**Comment by kou** [comment]
Sorry. I missed this.

The `[B]` XPath is invalid.

`self::*[B]` is a valid XPath for the use case.
