### ISSUE TITLE
ParseException on ruby 2.6 and 2.7

### ISSUE THREAD

**Issue by andriy-baran** [ruby/rexml#30]
ruby 2.5.0
```ruby
REXML::Document.new('<user></user>')  #=> <UNDEFINED> ... </>
```
ruby 2.6.3
```ruby
REXML::Document.new('<user></user>')
=> REXML::ParseException: Invalid attribute name: <</user>
Line: 1
Position: 13
Last 80 unconsumed characters:

```
gem version does not affect this

**Comment by kou** [comment]
I couldn't reproduce it:

```bash
$ ruby -v -r rexml/document -e "REXML::Document.new('<user></user>')"
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
```

Could you show backtrace?

**Comment by andriy-baran** [comment]
Related backtrace
```ruby
"/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:514:in `block in parse_attributes'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:510:in `loop'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:510:in `parse_attributes'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:378:in `pull_event'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/parsers/baseparser.rb:183:in `pull'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/parsers/treeparser.rb:23:in `parse'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/document.rb:288:in `build'",
 "/Users/admin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rexml-3.2.4/lib/rexml/document.rb:45:in `initialize'"
```

**Comment by andriy-baran** [comment]
Sorry, I found the code that patches the library
